export const roadItems = [
  { status: true, text: "Launch of basic Coin farming" },
  { status: true, text: "Launch of referral program" },
  { status: true, text: "Social quests" },
  { status: true, text: "100,000 activations" },
  { status: false, text: "Launch Drop game" },
  { status: false, text: "Leveling system (daily rewards)s" },
  { status: false, text: "Launch of quests in our game" },
  { status: false, text: "Launch of upgrades program" },
  { status: false, text: "500,000 activations" },
  { status: false, text: "1,000,000 activations" },
  { status: false, text: "Launch of quests from partners" },
  { status: false, text: "Launch Crypto Wallet" },
  { status: false, text: "Coming soon..." },
];
